// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteRun(arg1:number):Promise<void>;

export function GetAllRuns():Promise<Array<main.Run>>;

export function Greet(arg1:string):Promise<string>;

export function PrintAllRuns():Promise<void>;

export function SaveNewRun(arg1:main.Run):Promise<void>;

export function UpdateRun(arg1:main.Run):Promise<void>;
