// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function SaveRun(arg1:string,arg2:number,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;
