// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllRuns() {
  return window['go']['main']['App']['GetAllRuns']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function PrintAllRuns() {
  return window['go']['main']['App']['PrintAllRuns']();
}

export function SaveNewRun(arg1) {
  return window['go']['main']['App']['SaveNewRun'](arg1);
}

export function UpdateRun(arg1) {
  return window['go']['main']['App']['UpdateRun'](arg1);
}
